spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///mysmartplatform?useUnicode=true&useSSL=false&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8086