server:
  port: 11000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone : http://localhost:10000/eureka/
spring:
  application:
    name: addressproviderhystrix10