server:
  port: 20000
spring:
  application:
    name: configserver16
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhang-chunke/spring-cloud-config
          username: 19861904990
          password: sx91989918
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone : http://localhost:10000/eureka