server:
  port: 11000

spring:
  application:
    name: addressproviderconsul22 #当前程序的名字,eureka客户端会把这个信息带到server,server会按照这个名字进行区分保存数据
  cloud:
    inetutils:
      ignored-interfaces: [ 'VMware.*' ]  #忽略以VMware开头的网卡,这样虚拟机的网络不会注册到注册中心,防止其他人无法访问
    consul:
      host: localhost #consule注册中心地址
      port: 8500 #consule注册中心端口
      discovery: #下面的部分是consul的配置,很多配置本身就是默认值,只是介绍下
        heartbeat:
          enabled: true #开启心跳检查
        enabled: true #开启服务发现
        # 启用服务注册,默认就是true
        register: true
        # 服务停止时取消注册
        deregister: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        # 执行监控检查的频率
        health-check-interval: 30s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        # 健康检查的路径
        health-check-path: /actuator/health
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
      #  service-name: ${spring.application.name} #和上面的id二选一即可